apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisgraph-deployment
spec:
  selector:
    matchLabels:
      app: redisgraph-deployment
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: redisgraph-deployment
    spec:
      containers:
      - name: redisgraph-deployment
        image: redislabs/redisgraph
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redisgraph-all-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redisgraph-deployment
