apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisgraph
spec:
  selector:
    matchLabels:
      app: redisgraph
  replicas: 6 
  template: 
    metadata:
      labels:
        app: redisgraph
    spec:
      containers:
      - name: redisgraph
        image: redislabs/redisgraph
        ports:
        - containerPort: 8001
        - containerPort: 8443
        - containerPort: 9443
        - containerPort: 8004
        - containerPort: 8010
        - containerPort: 8011
        securityContext:
          capabilities:
            add:
              - SYS_RESOURCE
---             
apiVersion: v1
kind: Service
metadata:
  name: redisservice
  labels:
    app: redisservice
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: api1
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: api2
  - port: 9443
    targetPort: 9443
    protocol: TCP
    name: api3
  - port: 8004
    targetPort: 8004
    protocol: TCP
    name: api4
  - port: 8010
    targetPort: 8010
    protocol: TCP
    name: api5
  - port: 8011
    targetPort: 8011
    protocol: TCP
    name: api6
  selector:
    app: redisgraph